INSERT INTO articles (
	`author`
,	`title`
,	`content`
,	`description`
,	`created_at`
,	`image_url`
,	`country_origin`
) VALUES (
	"BBC Sport"
,	"Man Utd 0-2 PSG: Kimpembe and Mbappe earn win for PSG"
,	"<p>Manchester United must mount a miraculous recovery operation to keep their Champions League campaign alive after they were overpowered by Paris St-Germain at Old Trafford.</p><p>Second half goals from Presnel Kimpembe and Kylian Mbappe secured victory for the French champions, with Paul Pogba sent off for two yellow cards late on.</p><p>United\'s revival with 10 wins in 11 games under interim manager Ole Gunnar Solskjaer raised hopes that this was the night they could reclaim their place in Europe\'s elite.</p><p>Instead, they were outclassed by PSG to suffer their first European home defeat by a margin of more than one goal and will now need to produce something remarkable in Paris on 6 March to stand a chance of advancing to the Champions League quarter-finals.</p><p>Solskjaer\'s hopes were hampered by first-half injuries to Jesse Lingard and Anthony Martial but PSG made light of the absence of injured Brazilian superstar Neymar and striker Edinson Cavani.</p><p>Former Manchester United misfit Angel Di Maria was their tormentor, his 53rd minute corner allowing Kimpembe, arguably fortunate to still be on the pitch, to escape the attentions of Nemanja Matic and sidefoot past David De Gea.</p><p>And it was fitting that the brilliant Mbappe, whose searing pace was a threat all night, enhanced PSG\'s position of superiority when he turned Di Maria\'s inviting cross past the exposed De Gea on the hour.</p><p>If United\'s plight was not bad enough already, it was made worse when Pogba was sent off for a second yellow card in the final minute of normal time and will miss the second leg.</p>"
,	"Paris St-Germain stun Manchester United with a dominant performance at Old Trafford to take charge of their Champions League last 16 tie."
,	"2019-02-12 22:12:36"
,	"https://ichef.bbci.co.uk/onesport/cps/624/cpsprodpb/BE52/production/_105622784_mbappegoal.jpg"
,	"England"
),
(
	"BBC Sport"
,	"Oldham Athletic 4-1 Yeovil Town: Paul Scholes wins first game as manager"
,	"<p>Paul Scholes made a winning start as Oldham Athletic manager against Yeovil Town in League Two.</p><p>The ex-Manchester United and England midfielder was appointed on Monday by the club he followed as a child.</p><p>Jose Baxter curled in a shot to put Oldham ahead in first-half stoppage time and Callum Lang headed in a second just after the break.</p><p>Bevis Mugabi stabbed in a goal back for Yeovil before late goals from Mohammed Maouche and Christopher Missilou.</p><p>The two strikes that wrapped up victory for the Latics were both fine efforts from outside the penalty area.</p><p>Scholes said: \"It was nice, but it\'s just a start. That\'s all it is. I know there are tougher tests ahead, starting with Saturday against Crewe, who are going really well.</p><p>\"4-1 doesn\'t reflect how difficult the night was. Yeovil made it difficult for us.</p><p>\"I\'m really pleased with the goals. I said in my press conference on Monday that I knew there was talent in this squad.</p><p>\"I want them to enjoy and express themselves and the way you do that is by scoring goals.\"</p><p>Scholes, 44, is the fourth former England player to make his managerial debut in the English Football League this season.</p><p>Derby\'s Frank Lampard was victorious in his first league game as a manager in August, while Fleetwood\'s Joey Barton and Macclesfield\'s Sol Campbell both lost their first matches in charge.</p>"
,	"Ex-England midfielder Paul Scholes makes a winning start as Oldham manager against Yeovil in League Two."
,	"2019-02-12 21:51:12"
,	"https://ichef.bbci.co.uk/onesport/cps/624/cpsprodpb/0D0E/production/_105624330_scholes3.jpg"
,	"England"
),
(
	"ESPN"
,	"Conceicao: \"Porto will go through\""
,	"<p>Sergio Conceicao insists Porto \"deserved a draw\" in their 2-1 defeat to Roma and is \"convinced we’ll go through to the quarter-final.\"</p><p>Nicolò Zaniolo had put the Giallorossi 2-0 up with a brace, but Adrian Lopez made the most of a wayward Soares shot to give Porto a potentially decisive away goal.</p><p>The second leg of this Champions League Round of 16 is at the Estadio do Dragao on March 6.</p><p>\"My team managed to neutralise Roma’s strengths in the first half. We came close to scoring with Danilo’s header after the break and were in control with our best period of the game when Roma scored in fairly chaotic circumstances, with Yacine Brahimi down injured and confusion on the bench.\"</p><p>There were indeed some very tense scenes on the touchline just before that, as Brahimi had gone off for treatment, came back on and sat down on the ground when realising he could not continue.</p><p>He was a long way off the action, so Roma continued their move and almost scored.</p><p>This sparked a furious row between Conceicao and Eusebio Di Francesco, as the former Lazio wing-back has clearly still remembered some Italian insults.</p><p>\"Then we conceded the second goal off a ricochet, but did not stop fighting and the team reacted precisely the way I expected. This side has character and this was only the first half of the tie.</p><p>\"Our goal leaves everything open for the second leg. I do believe the fair result this evening would’ve been a draw. We have to be more solid defensively at the Dragao and more incisive upfront.</p><p>\"What we must not forget is that no opponent is comfortable when we step up the pace and intensity. We might not be the best team in the world, but we are the biggest fighters. I have no doubt about it.</p><p>\"We need to make some adjustments, but I am convinced we’ll go through to the quarter-final.\"</p><p>This was Porto\'s first Champions League defeat of the season after a draw and five victories.</p>"
,	"Sergio Conceicao insists Porto \"deserved a draw\" in their 2-1 defeat to Roma and is \"convinced we\'ll go through to the quarter-final.\""
,	"2019-02-13 01:00:00"
,	"https://www.football-italia.net/sites/default/files/imagecache/main_photo/[type]/[nid]/Conceicao-1902-glance-epa.jpg"
,	"Italy"
),
(
	"FourFourTwo"
,	"Herrera remains optimistic despite demoralising PSG defeat"
,	"<p>Ander Herrera insisted Manchester United must still believe they can turn around their Champions League tie with Paris Saint-Germain, despite suffering a 2-0 defeat at home in the first leg.</p><p>Presnel Kimpembe and Kylian Mbappe scored in the second half as PSG overcame the absences of Edinson Cavani and Neymar to triumph at Old Trafford.</p><p>The reverse was United\'s heaviest at home in European competition, while no side in the history of the Champions League has ever progressed from a knockout tie having lost the home first leg by two or more goals.</p><p>But Herrera pointed to their recent run of good form as a reason to remain optimistic.</p><p>United have recorded away wins over Tottenham and Arsenal - beating the latter in the FA Cup - under Ole Gunnar Solskjaer, though Tuesday\'s result was the Norwegian\'s first defeat since taking over on an interim basis.</p><p>\"I think the game was tight until the corner [from which Kimpembe scored]. After the first goal they played the way they wanted,\" Herrera told BT Sport. </p><p>\"After the first goal everything changes, it was under control and we were better until that moment. The game could have finished 0-0 if they hadn\'t scored from that corner, but they did.</p><p>\"After that they played on the counter, they have very quick players, but it was tight until the corner.</p><p>\"Now we have good examples, having won at Spurs and Arsenal - big teams, big games, and we will try to win away. We all are very optimistic and positive, it\'s just one result and we\'re in a good moment. We\'re going to continue.</p><p>\"It\'s a tough night and tomorrow will be a tough day but our focus is to stay in the top four and stay in the FA Cup.\"</p><p>United are next in action in the FA Cup, as they visit Chelsea in the fifth round of the competition. </p>"
,	"Manchester United face a tall order to reach the Champions League quarter-finals, but Ander Herrera believes they should not give up hope."
,	"2019-02-12 23:31:01"
,	"https://images.cdn.fourfourtwo.com/sites/fourfourtwo.com/files/herreracropped_1b5pbpc1c6cwj1m64b9mty84rl.jpg"
,	"Italy"
),
(
	"BBC Sport"
,	"Cardiff will be 'honourable' with Nantes on Sala transfer"
,	"<p>Chairman Mehmet Dalman says Cardiff will be \"honourable\" with Nantes over the £15m transfer for Emiliano Sala and has defended withholding a payment.</p><p>Dalman confirmed the French club are threatening legal action, but they are seeking \"clarification\" on the issue.</p><p>Sala\'s body was recovered from the wreckage of a crashed plane last week.</p><p>Dalman also issued strong backing to Neil Warnock over his connection with football agents, believing people have had \"knives out\" for Cardiff\'s manager.</p><p>Sala had been travelling to Cardiff in a light aircraft piloted by David Ibbotson that went missing over the English Channel on 21 January.</p><p>A fundraising appeal to fund an underwater search for the pilot has been set up.</p><p>Cardiff City owner Vincent Tan has boosted funds by donating £50,000 of his own money towards the appeal.</p><p>Confirming the Nantes action, Dalman said: \"Of course, if we are contractually obliged to pay them then of course we will. We are an honourable club.</p><p>\"But if we are not - and there are some anomalies in that - then surely you would expect me as the chairman and guardian of this club\'s interests to look into that and hold our position. That is what we are doing.</p><p>\"We are still in the process of gathering information and that process will be ongoing. And when we reach a level where we have enough information, I am sure we will sit down with Nantes and move forward.\"</p><p>Dalman says Cardiff are looking to get a full picture of events.</p><p>\"They [Nantes] have asked for what they believe is the money due to them and there is a process and they have initiated that process,\" he added.</p><p>\"What we are saying is, that we are not in agreement with that process given the extraordinary events that have taken place and the tragic circumstances. We are not making any positive or negative statements.</p><p>\"We are simply saying, please understand there are a lot of questions which need to be answered and that is what we are trying to do.\"</p>"
,	"Chairman Mehmet Dalman says Cardiff will be \"honourable\" with Nantes over the £15m transfer for Emiliano Sala and has defended withholding a payment."
,	"2019-02-12 15:51:14"
,	"https://ichef.bbci.co.uk/onesport/cps/624/cpsprodpb/FA97/production/_105615146_cdf_250217_ge_cardiff_v_fulham_60.jpg"
,	"England"
);
